[project]
name = "nvanderw_voting"
version = "0.0.1"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tools.setuptools.packages.find]
where = ["voting"]

[tool.setuptools.package-data]
"*" = ["*.csv"]